# version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URI=<your_mongodb_uri>
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/usr/src/app
    command: npm start

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    stdin_open: true
    volumes:
      - ./frontend:/app
